[application]

# App (Project) Name
name = "birdtalk"

# Dioxus App Default Platform
# desktop, web
default_platform = "fullstack"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

# [bundle]
# resources = ["**/*.png", "**/*.mp3"]

[web.app]

# HTML title tag content
title = "birdtalk"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]
