name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install nightly rustfmt
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt

      - name: Install stable clippy
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
          override: true

      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-on-failure: "true"

      - name: Install npm
        uses: actions/setup-node@v4

      - name: Install npm deps
        working-directory: app
        run: npm ci;

      # dotenvy requires this
      - run: cp .env.example .env

      - name: Format check
        run: cargo +nightly fmt --all -- --check

      - name: Lint check
        run: cargo +stable clippy --all-features -- -D warnings

      - name: Test
        run: cargo test

      - name: Install Dioxus
        # run: cargo binstall dioxus-cli@0.6.0-alpha.2 -y --force
        run: cargo install --git https://github.com/DioxusLabs/dioxus.git --rev 87c2f64f134756578f6cf9e12fd085b9bb03c5c7 dioxus-cli --locked

      - name: Build app
        working-directory: app
        run: dx build --platform web --features web
